# Generated by Django 3.2.25 on 2025-12-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20251209_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_logins',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='weekly_logins',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
