# Generated by Django 3.2.25 on 2026-01-31 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20251209_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginactivity',
            name='attempted_username',
            field=models.CharField(blank=True, help_text='Username/email attempted during login (for failed attempts on non-existent users)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loginactivity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
