# Generated by Django 3.2.25 on 2026-06-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_role',
            field=models.CharField(choices=[('regular', 'Regular'), ('staff', 'Staff'), ('superuser', 'Superuser')], default='regular', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='staff_access_granted',
            field=models.BooleanField(default=False),
        ),
    ]
